"""core schema: submissions, tokens, correlations

Revision ID: a7e459274457
Revises: 
Create Date: 2026-09-01 18:56:27.382999
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = 'a7e459274457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlations',
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('indicator_type', sa.String(length=16), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('shared_techniques', sa.JSON(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('reduced_fidelity', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('correlation_id', name=op.f('pk_correlations')),
    schema='core'
    )
    op.create_index(op.f('ix_core_correlations_campaign_id'), 'correlations', ['campaign_id'], unique=False, schema='core')
    op.create_table('submissions',
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('institution_ref', sa.String(length=64), nullable=False),
    sa.Column('technique_set', sa.JSON(), nullable=False),
    sa.Column('sector', sa.String(length=16), nullable=False),
    sa.Column('size_band', sa.String(length=16), nullable=False),
    sa.Column('severity_band', sa.String(length=16), nullable=False),
    sa.Column('ts_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('obligation_receipt_hash', sa.String(length=64), nullable=True),
    sa.Column('obligation_authority', sa.String(length=32), nullable=True),
    sa.Column('obligation_filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclosure_rung', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_submissions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_submissions_institution_ref'), 'submissions', ['institution_ref'], unique=False, schema='core')
    op.create_table('correlation_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('institution_ref', sa.String(length=64), nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['correlation_id'], ['core.correlations.correlation_id'], name=op.f('fk_correlation_members_correlation_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correlation_members')),
    schema='core'
    )
    op.create_index(op.f('ix_core_correlation_members_correlation_id'), 'correlation_members', ['correlation_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_correlation_members_institution_ref'), 'correlation_members', ['institution_ref'], unique=False, schema='core')
    op.create_table('submission_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=64), nullable=False),
    sa.Column('indicator_type', sa.String(length=16), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['core.submissions.submission_id'], name=op.f('fk_submission_tokens_submission_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_tokens')),
    schema='core'
    )
    op.create_index(op.f('ix_core_submission_tokens_submission_id'), 'submission_tokens', ['submission_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_submission_tokens_token'), 'submission_tokens', ['token'], unique=False, schema='core')
    op.create_index('ix_submission_tokens_token_type', 'submission_tokens', ['token', 'indicator_type'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_tokens_token_type', table_name='submission_tokens', schema='core')
    op.drop_index(op.f('ix_core_submission_tokens_token'), table_name='submission_tokens', schema='core')
    op.drop_index(op.f('ix_core_submission_tokens_submission_id'), table_name='submission_tokens', schema='core')
    op.drop_table('submission_tokens', schema='core')
    op.drop_index(op.f('ix_core_correlation_members_institution_ref'), table_name='correlation_members', schema='core')
    op.drop_index(op.f('ix_core_correlation_members_correlation_id'), table_name='correlation_members', schema='core')
    op.drop_table('correlation_members', schema='core')
    op.drop_index(op.f('ix_core_submissions_institution_ref'), table_name='submissions', schema='core')
    op.drop_table('submissions', schema='core')
    op.drop_index(op.f('ix_core_correlations_campaign_id'), table_name='correlations', schema='core')
    op.drop_table('correlations', schema='core')
    # ### end Alembic commands ###
