"""
Mutual TLS between a remote connector and the core.

Institution C runs on separate hardware and reaches the core across the public
internet. Connectors A and B share a kernel with core, so their isolation is Docker's
word; C shares nothing, so it has to prove who it is over an untrusted network.

A bearer token would not do that. A token in an environment variable is readable by
anyone with the image, the compose file, or a log line, and it is the same secret for
every request forever. A client certificate is bound to a private key that never
leaves the institution, and an unauthenticated connector fails the TLS handshake — it
never reaches application code at all.

These tests stand up a real TLS server with the certificates
`deploy/make-certs.sh` produces and check three things: the right certificate gets in,
no certificate is refused, and a certificate from a different CA is refused. They are
local — a loopback socket, no network — so they run in the default suite.
"""

from __future__ import annotations

import http.server
import socket
import ssl
import subprocess
import sys
import threading
from pathlib import Path

import httpx
import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [
    str(ROOT / "packages" / "contracts"),
    str(ROOT / "services" / "connector"),
]

CERTS = ROOT / "deploy" / "certs"


@pytest.fixture(scope="module")
def certificates(tmp_path_factory):
    """
    Real certificates, generated by the real script.

    Generated fresh rather than committed: a private key in version control is a
    private key on every laptop that ever cloned the repository.
    """
    if not (CERTS / "ca.crt").exists():
        pytest.skip(f"no certificates at {CERTS}; run deploy/make-certs.sh")

    # A certificate from a DIFFERENT authority, to prove the check is on the signature
    # rather than on merely presenting something.
    outsider = tmp_path_factory.mktemp("outsider")
    subprocess.run(
        ["bash", str(ROOT / "deploy" / "make-certs.sh"), str(outsider), "psd_outsider01"],
        check=True, capture_output=True, cwd=ROOT,
    )
    return {"trusted": CERTS, "outsider": outsider}


@pytest.fixture
def mtls_server(certificates):
    """A TLS server that requires a client certificate signed by the federation CA."""
    trusted = certificates["trusted"]

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_POST(self):
            self.send_response(200)
            self.send_header("content-type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"accepted": true}')

        def log_message(self, *args):
            pass

    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(trusted / "core.crt", trusted / "core.key")
    context.load_verify_locations(cafile=trusted / "ca.crt")
    context.verify_mode = ssl.CERT_REQUIRED          # the whole point

    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        port = probe.getsockname()[1]

    server = http.server.HTTPServer(("127.0.0.1", port), Handler)
    server.socket = context.wrap_socket(server.socket, server_side=True)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"https://localhost:{port}"
    finally:
        server.shutdown()
        server.server_close()


def test_a_connector_with_its_certificate_is_admitted(mtls_server, certificates):
    """Institution C, submitting from other hardware. This must work."""
    trusted = certificates["trusted"]
    # An explicit SSLContext, exactly as the connector builds one. httpx's `cert=`
    # keyword silently fails to present the certificate on 0.28 — the reason
    # _core_tls returns a context instead.
    context = ssl.create_default_context(cafile=str(trusted / "ca.crt"))
    context.load_cert_chain(str(trusted / "psd_emcap03.crt"), str(trusted / "psd_emcap03.key"))
    with httpx.Client(verify=context, timeout=10) as client:
        response = client.post(f"{mtls_server}/v1/submissions", json={"probe": True})
    assert response.status_code == 200
    assert response.json()["accepted"] is True


def test_a_connector_without_a_certificate_fails_the_handshake(mtls_server, certificates):
    """
    Refused at the TLS layer, before any application code runs. That is the
    difference between authentication and a permission check someone can forget.
    """
    with (
        httpx.Client(verify=str(certificates["trusted"] / "ca.crt"), timeout=10) as client,
        pytest.raises((httpx.ConnectError, ssl.SSLError, httpx.ReadError)),
    ):
        client.post(f"{mtls_server}/v1/submissions", json={"probe": True})


def test_a_certificate_from_another_authority_is_refused(mtls_server, certificates):
    """
    Presenting *a* certificate is not enough; it must be signed by the federation CA.
    Anyone can generate a self-signed certificate claiming any pseudonym.
    """
    outsider = certificates["outsider"]
    context = ssl.create_default_context(cafile=str(certificates["trusted"] / "ca.crt"))
    context.load_cert_chain(str(outsider / "psd_outsider01.crt"),
                            str(outsider / "psd_outsider01.key"))
    with (
        httpx.Client(verify=context, timeout=10) as client,
        pytest.raises((httpx.ConnectError, ssl.SSLError, httpx.ReadError)),
    ):
        client.post(f"{mtls_server}/v1/submissions", json={"probe": True})


def test_the_connector_refuses_to_downgrade_when_its_certificate_is_missing():
    """
    A connector configured for mutual TLS whose certificate has gone must fail loudly.
    Falling back to an unauthenticated connection would look identical to a connector
    that never needed one — and it would be sending boundary payloads to something it
    has not authenticated.
    """
    from marsad_connector.main import _core_tls

    class Config:
        core_client_cert = "/nonexistent/psd_emcap03.crt"
        core_client_key = "/nonexistent/psd_emcap03.key"
        core_ca_bundle = ""

    with pytest.raises(RuntimeError, match="Refusing to fall back"):
        _core_tls(Config())


def test_the_connector_builds_an_ssl_context_not_an_httpx_cert_kwarg(certificates):
    """
    Regression guard for a bug that would have shipped.

    httpx 0.28 accepts `cert=(crt, key)` and then does not present the certificate.
    The server refuses the handshake, the connector reports "core unreachable" and
    queues locally — so a TLS misconfiguration looks exactly like a network outage,
    which is the hardest kind of failure to diagnose. The helper must return a
    configured SSLContext.
    """
    from marsad_connector.main import _core_tls

    trusted = certificates["trusted"]

    class Config:
        core_client_cert = str(trusted / "psd_emcap03.crt")
        core_client_key = str(trusted / "psd_emcap03.key")
        core_ca_bundle = str(trusted / "ca.crt")

    options = _core_tls(Config())
    assert "cert" not in options, "the cert= keyword does not work on httpx 0.28"
    assert isinstance(options["verify"], ssl.SSLContext)
    assert options["verify"].get_ca_certs(), "the CA bundle was not loaded"


def test_no_tls_material_configured_means_plain_http():
    """A core on the same host behind Docker isolation does not need a certificate."""
    from marsad_connector.main import _core_tls

    class Config:
        core_client_cert = ""
        core_client_key = ""
        core_ca_bundle = ""

    assert _core_tls(Config()) == {}


def test_the_client_certificate_carries_a_pseudonym_not_a_firm_name(certificates):
    """
    `institution_ref` is a rotating pseudonym everywhere else in the system, and the
    certificate subject is no exception — it is the identity the core authorises on,
    and a firm name there would undo the pseudonymity the whole design rests on.
    """
    subject = subprocess.run(
        ["openssl", "x509", "-in", str(certificates["trusted"] / "psd_emcap03.crt"),
         "-noout", "-subject"],
        capture_output=True, text=True, check=True,
    ).stdout

    assert "psd_emcap03" in subject
    for firm_name in ("Emirates", "Capital", "Al Maha", "Gulf"):
        assert firm_name not in subject, f"the certificate subject names the firm: {subject}"
