"""edge schema: local incidents and extraction provenance

Revision ID: dad425257b81
Revises: 
Create Date: 2026-09-01 18:56:28.264165
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = 'dad425257b81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('narrative_normalised', sa.Text(), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('raw_email', sa.Text(), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=False),
    sa.Column('techniques', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('evidence_paths', sa.JSON(), nullable=False),
    sa.Column('obligation_receipt', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_submission_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confirmed_by', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_local_incidents')),
    schema='edge'
    )
    op.create_index(op.f('ix_edge_local_incidents_expires_at'), 'local_incidents', ['expires_at'], unique=False, schema='edge')
    op.create_table('extraction_provenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('needs_attention', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['edge.local_incidents.id'], name=op.f('fk_extraction_provenance_incident_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_provenance')),
    schema='edge'
    )
    op.create_index(op.f('ix_edge_extraction_provenance_incident_id'), 'extraction_provenance', ['incident_id'], unique=False, schema='edge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edge_extraction_provenance_incident_id'), table_name='extraction_provenance', schema='edge')
    op.drop_table('extraction_provenance', schema='edge')
    op.drop_index(op.f('ix_edge_local_incidents_expires_at'), table_name='local_incidents', schema='edge')
    op.drop_table('local_incidents', schema='edge')
    # ### end Alembic commands ###
